# config.yaml
data_generation:
  num_users: 100
  num_articles: 200
  num_videos: 200
  start_date: "2022-01-01"
  end_date: "2023-10-20"
  creators_authors:
    - "John Trader"
    - "Jane Market"
    - "FuturesAcademy"
    - "TradeEasy Pro"
    - "Alpha Analyst"
    - "RiskManager Rick"
  media_tags:
    - "Beginner"
    - "Intermediate"
    - "Advanced"
    - "Risk Management"
    - "Technical Analysis"
    - "Fundamental Analysis"
    - "Options"
    - "Futures"
    - "ES"
    - "CL"
    - "GC"
    - "Trading Psychology"
    - "Market Outlook"
  video_lengths_seconds: [300, 450, 600, 750, 900, 1200, 1500, 1800]
  experience_levels: ["Beginner", "Intermediate", "Advanced"]
  trading_goals_list:
    - "Improve risk management"
    - "Learn about volatility trading"
    - "Understand order flow"
    - "Master technical analysis"
    - "Learn about specific instruments"
    - "Improve trading psychology"
    - "Generate consistent profits"
    - "Diversify trading strategies"
    - "Learn about options trading"
  preferred_assets_list: ["ES", "NQ", "CL", "GC", "ZN", "ZB", "EURUSD", "BTC", "ETH"]
  order_types: ["Market", "Limit", "Stop", "Stop-Limit"]
  frequencies: ["Low", "Medium", "High"]

bigquery:
  dataset_name: "trading_platform_data"
  users_table_name: "users"
  media_table_name: "media_content"
  recommendations_table_name: "user_recommendations"

embedding_model:
  publisher: "google"
  model_name: "text-embedding-004" # Or latest version
  max_retries: 3
  batch_size: 5 # Vertex AI Embedding API has a limit per request

batch_recommendation:
  top_n_to_store: 50 # Store more recommendations than needed for online
  similarity_metric: "cosine" # or "euclidean"

online_recommendation:
  top_n_to_retrieve: 5